In [10]:
import numpy as np
b=[0.1,0.9]
a=[0,1]
c=np.random.choice(a,size=(2),p=b)
print(c)

[1 1]


In [7]:
l=len(a)
print(l)

2


In [8]:
l+=1

In [9]:
print(1/l)

0.3333333333333333


In [11]:
num=5
n=np.random.choice([1, 0],size=(num),p=[1/num, 1 - 1/num])
print(n)

[0 0 1 0 0]


In [12]:
a=[0,1,-1]
np.abs(a)

array([0, 1, 1])

In [13]:
a=np.array([0,1,-1])

TypeError: Required argument 'object' (pos 1) not found

In [15]:
a=np.array([0,1,-1])
b=np.array([4,4,4])
b=np.row_stack((b,a))

In [17]:
b[1:,]

array([[ 0,  1, -1]])

In [22]:
a=np.array([0,1,-1,0,0,0,0])
j = np.random.choice(np.where(a == 0)[0])
print(j)
print(a[j])

6
0


In [36]:
a=np.array([0,1,-1,0,0,0,0])
c= np.where(a==0)
print(len(c[0]))
c
a[c]=2

5


In [33]:
a

array([ 2,  1, -1,  2,  2,  2,  2])

In [26]:
a

array([ 2,  1, -1,  2,  2,  2,  2])

In [37]:
a=np.array([1,2,3])
b=np.ones(3)
print(a)
print(b)
c=np.column_stack((a,b))
print(c)
print()

[1 2 3]
[1. 1. 1.]
[[1. 1.]
 [2. 1.]
 [3. 1.]]

